from __future__ import annotations

import uuid
from datetime import date, datetime

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PgEnum, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base, DailyBriefStatus


class DailyBrief(Base):
    """One generated daily brief per user per day (weather/news/phrases/challenge
    segments in `content_json`). Generated by the Celery worker; one row per
    (user_id, brief_date)."""

    __tablename__ = "daily_briefs"
    __table_args__ = (
        sa.UniqueConstraint(
            "user_id", "brief_date", name="uq_daily_briefs_user_id_brief_date"
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )
    user_id: Mapped[int | None] = mapped_column(
        sa.ForeignKey("users.id", onupdate="CASCADE", ondelete="RESTRICT"),
        index=True,
    )
    brief_date: Mapped[date] = mapped_column(sa.Date, nullable=False, index=True)
    status: Mapped[DailyBriefStatus] = mapped_column(
        PgEnum(DailyBriefStatus, name="daily_brief_status"),
        server_default=DailyBriefStatus.QUEUED.value,
        nullable=False,
    )
    progress: Mapped[int | None] = mapped_column(
        sa.Integer, default=0, server_default=sa.text("0")
    )
    current_step: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    content_json: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    error_message: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    created_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), server_default=sa.func.now()
    )
    updated_at: Mapped[datetime | None] = mapped_column(
        sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()
    )
