"""Celery tasks that generate per-user daily briefs (F2).

Extends the Gemini pipeline: one brief per (user_id, brief_date), generated by
`generate_daily_brief`; `dispatch_daily_briefs` fans out to all users (called by
celery beat). Requires Gemini + Redis + DB at runtime (not exercised in tests).
"""
from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from datetime import date, datetime, timezone

from sqlalchemy import select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

import app.core.ai as AI
from app.core.agents.usage import pop_usages
from app.core.config import settings
from app.core.database import DailyBriefStatus
from app.models import DailyBrief, User
from app.services.token_usage import TokenUsageService
from app.worker.celery_app import celery_app

logger = logging.getLogger(__name__)
UTC = timezone.utc

_WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
_MONTHS = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
]


def _date_label(d: date) -> str:
    return f"{_WEEKDAYS[d.weekday()]}, {_MONTHS[d.month - 1]} {d.day}"


@asynccontextmanager
async def _session_scope():
    engine = create_async_engine(settings.DB_URL, echo=False, future=True)
    session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with session() as db:
        try:
            yield db
        finally:
            await db.close()
            await engine.dispose()


async def _get_or_create(db: AsyncSession, user_id: int, brief_date: date) -> DailyBrief:
    res = await db.execute(
        select(DailyBrief).where(
            DailyBrief.user_id == user_id, DailyBrief.brief_date == brief_date
        )
    )
    brief = res.scalar_one_or_none()
    if brief is None:
        brief = DailyBrief(
            user_id=user_id, brief_date=brief_date, status=DailyBriefStatus.QUEUED
        )
        db.add(brief)
        try:
            await db.commit()
            await db.refresh(brief)
        except IntegrityError:
            # Another worker created the (user, date) brief first — load theirs.
            await db.rollback()
            res = await db.execute(
                select(DailyBrief).where(
                    DailyBrief.user_id == user_id,
                    DailyBrief.brief_date == brief_date,
                )
            )
            brief = res.scalar_one()
    return brief


async def _news_context(db: AsyncSession, user_id: int) -> str:
    """Best-effort recent-news context for the 'happening' segment."""
    try:
        from app.services.news import get_cached_feed

        feed = await get_cached_feed(db, user_id, limit_per_topic=3)
        items = (feed or {}).get("items", [])[:4]
        lines = []
        for n in items:
            title = getattr(n, "title", None)
            summary = getattr(n, "summary", None) or ""
            if title:
                lines.append(f"- {title}: {summary}".strip())
        return "\n".join(lines)
    except Exception:  # pragma: no cover - best effort
        return ""


async def _generate_daily_brief(user_id: int, brief_date_iso: str | None):
    brief_date = (
        date.fromisoformat(brief_date_iso)
        if brief_date_iso
        else datetime.now(UTC).date()
    )
    async with _session_scope() as db:
        brief = await _get_or_create(db, user_id, brief_date)
        if brief.status == DailyBriefStatus.COMPLETED:
            return  # idempotent: already generated today

        await db.execute(
            update(DailyBrief)
            .where(DailyBrief.id == brief.id)
            .values(
                status=DailyBriefStatus.GENERATING,
                current_step="Generating daily brief…",
                progress=10,
            )
        )
        await db.commit()

        news_context = await _news_context(db, user_id)

        result = await AI.generate_daily_brief(
            city="Toronto",  # TODO: pull from user profile/nationality
            level=6,
            date_label=_date_label(brief_date),
            news_context=news_context,
        )
        try:
            await TokenUsageService.record_all(
                db, pop_usages(result), user_id=user_id, source="gemini"
            )
        except Exception:  # pragma: no cover
            logger.warning("daily brief: token usage recording failed", exc_info=True)

        content = {
            "date": result.get("date") or _date_label(brief_date),
            "segments": result.get("segments", []),
        }

        await db.execute(
            update(DailyBrief)
            .where(DailyBrief.id == brief.id)
            .values(
                content_json=content,
                status=DailyBriefStatus.COMPLETED,
                current_step="Daily brief ready",
                progress=100,
            )
        )
        await db.commit()


async def _mark_failed(user_id: int, brief_date_iso: str | None, error: Exception):
    brief_date = (
        date.fromisoformat(brief_date_iso)
        if brief_date_iso
        else datetime.now(UTC).date()
    )
    async with _session_scope() as db:
        await db.execute(
            update(DailyBrief)
            .where(
                DailyBrief.user_id == user_id, DailyBrief.brief_date == brief_date
            )
            .values(
                status=DailyBriefStatus.FAILED,
                error_message=str(error),
                current_step="Daily brief generation failed",
            )
        )
        await db.commit()


@celery_app.task(
    name="app.worker.daily_brief_tasks.generate_daily_brief",
    bind=True,
    max_retries=3,
)
def generate_daily_brief(self, user_id: int, brief_date_iso: str | None = None):
    try:
        asyncio.run(_generate_daily_brief(int(user_id), brief_date_iso))
    except Exception as e:  # pragma: no cover - needs Redis/Gemini
        if int(getattr(self.request, "retries", 0) or 0) < 3:
            raise self.retry(exc=e, countdown=5)
        asyncio.run(_mark_failed(int(user_id), brief_date_iso, e))
        raise


@celery_app.task(name="app.worker.daily_brief_tasks.dispatch_daily_briefs")
def dispatch_daily_briefs():
    asyncio.run(_dispatch_daily_briefs())


async def _dispatch_daily_briefs():
    async with _session_scope() as db:
        res = await db.execute(select(User.id))
        for (uid,) in res.all():
            generate_daily_brief.apply_async(args=[uid], queue="daily_brief")


def enqueue_daily_brief(user_id: int, brief_date_iso: str | None = None) -> None:
    """On-demand dispatch from an endpoint (mirrors the podcast enqueue)."""
    generate_daily_brief.apply_async(args=[user_id, brief_date_iso], queue="daily_brief")
