"""drop redundant duplicate indexes

Revision ID: 5133a004f071
Revises: aaed617c4069
Create Date: 2026-06-17 18:39:44.110858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5133a004f071'
down_revision: Union[str, Sequence[str], None] = 'aaed617c4069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_corrections_grammar_id_uuid'), table_name='grammar_corrections')
    op.drop_index(op.f('ix_password_reset_tokens_user_id_copy1'), table_name='signup_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_password_reset_tokens_user_id_copy1'), 'signup_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_corrections_grammar_id_uuid'), 'grammar_corrections', ['grammar_id'], unique=False)
    # ### end Alembic commands ###
