"""initial baseline

Captures the full schema as it existed when the project adopted Alembic
(previously created via Base.metadata.create_all). Existing databases are
already stamped at this revision; fresh databases build the whole schema
by running it.

Revision ID: aaed617c4069
Revises: 
Create Date: 2026-06-17 17:30:27.312704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.database

# revision identifiers, used by Alembic.
revision: str = 'aaed617c4069'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'support'"), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('learning_goals',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('news_topics',
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_search_prompt', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('geo_codes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('update_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('preauth_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_nonce', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_article_refresh_jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='queued', nullable=False),
    sa.Column('topic_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('total_topics', sa.Integer(), server_default='0', nullable=False),
    sa.Column('succeeded_topics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('failed_topics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=64), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', app.core.database.CITEXT(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('last_login_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('users_email_unique_active', 'users', ['email'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_resource_id'), 'admin_audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_resource_type'), 'admin_audit_logs', ['resource_type'], unique=False)
    op.create_table('admin_notes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notes_admin_id'), 'admin_notes', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_notes_user_id'), 'admin_notes', ['user_id'], unique=False)
    op.create_table('grammar_suggestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('OK', 'ERROR', name='ai_status'), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suggestions_user_id', 'grammar_suggestions', ['user_id'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_news_items_topic_id'), 'news_items', ['topic_id'], unique=False)
    op.create_table('password_reset_codes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_codes_user_id'), 'password_reset_codes', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('podcast_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'GENERATING_SCRIPT', 'GENERATING_AUDIO', 'COMPLETED', 'FAILED', name='podcast_job_status'), server_default='QUEUED', nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('current_step', sa.Text(), nullable=True),
    sa.Column('script_json', sa.Text(), nullable=True),
    sa.Column('total_segments', sa.Integer(), nullable=True),
    sa.Column('completed_segments', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('audio_folder', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_jobs_user_id'), 'podcast_jobs', ['user_id'], unique=False)
    op.create_table('session_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by'], ['session_tokens.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_tokens_user_id', 'session_tokens', ['user_id'], unique=False)
    op.create_table('signup_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fki_signup_tokens_user_id_fkey', 'signup_tokens', ['user_id'], unique=False)
    op.create_index('ix_password_reset_tokens_user_id_copy1', 'signup_tokens', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('CREATED', 'IN_PROGRESS', 'FAILED', 'COMPLETED', name='task_status'), server_default='CREATED', nullable=False),
    sa.Column('cover_title', sa.Text(), nullable=True),
    sa.Column('voice_address', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_user_id', 'tasks', ['user_id'], unique=False)
    op.create_table('token_usage_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('usage_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usage_date', 'user_id', 'source', 'model_name', name='uq_token_usage_daily')
    )
    op.create_index(op.f('ix_token_usage_daily_source'), 'token_usage_daily', ['source'], unique=False)
    op.create_index(op.f('ix_token_usage_daily_usage_date'), 'token_usage_daily', ['usage_date'], unique=False)
    op.create_index(op.f('ix_token_usage_daily_user_id'), 'token_usage_daily', ['user_id'], unique=False)
    op.create_table('tone_adjustments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_tone_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('OK', 'ERROR', name='ai_status'), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('adjusted', sa.Text(), nullable=False),
    sa.Column('target_tone', sa.Text(), nullable=False),
    sa.Column('user_action', postgresql.ENUM('APPROVED', 'REJECTED', name='grammar_user_action'), nullable=True),
    sa.Column('user_action_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_tone_id'], ['tone_adjustments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tone_adjustments_id', 'tone_adjustments', ['user_id'], unique=False)
    op.create_index('idx_tone_adjustments_parent_tone_id', 'tone_adjustments', ['parent_tone_id'], unique=False)
    op.create_table('topic_articles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_articles_topic_id'), 'topic_articles', ['topic_id'], unique=False)
    op.create_table('topic_podcast_scripts',
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='READY', nullable=False),
    sa.Column('script_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('topic_refresh_jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='queued', nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=24), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_refresh_jobs_topic_id'), 'topic_refresh_jobs', ['topic_id'], unique=False)
    op.create_table('translate_texts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('OK', 'ERROR', name='ai_status'), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('translated', sa.Text(), nullable=False),
    sa.Column('target_lang', sa.Text(), nullable=False),
    sa.Column('user_action', postgresql.ENUM('APPROVED', 'REJECTED', name='grammar_user_action'), nullable=True),
    sa.Column('user_action_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_translate_texts_id', 'translate_texts', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'goal_id')
    )
    op.create_table('user_learning_insights',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('misspelled_words', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('grammar_issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('linguistic_profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('estimated_clb_level', sa.String(length=20), nullable=True),
    sa.Column('language_development_grammar', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('vocabulary_improvement', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('learning_path', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_level', sa.SmallInteger(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('language_level BETWEEN 4 AND 9', name='ck_user_preferences_language_level'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    op.create_table('user_topic_categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['topic_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('user_topic_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.String(length=64), nullable=True),
    sa.Column('feedback', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.topic_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic_feedback')
    )
    op.create_index(op.f('ix_user_topic_feedback_topic_id'), 'user_topic_feedback', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_feedback_user_id'), 'user_topic_feedback', ['user_id'], unique=False)
    op.create_table('user_topic_preferences',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.String(length=64), nullable=True),
    sa.Column('is_following', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('weight', sa.Integer(), server_default='0', nullable=False),
    sa.Column('assigned_by', sa.String(length=24), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('geo_code', sa.String(length=8), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['news_topics.topic_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_topic_preferences_topic_id'), 'user_topic_preferences', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_preferences_user_id'), 'user_topic_preferences', ['user_id'], unique=False)
    op.create_table('feed_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('SUGGESTED', 'GENERATING', 'READY', 'LISTENED', 'ARCHIVED', name='feed_item_status'), server_default='SUGGESTED', nullable=False),
    sa.Column('podcast_job_id', sa.UUID(), nullable=True),
    sa.Column('last_segment_index', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['podcast_job_id'], ['podcast_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_items_user_id'), 'feed_items', ['user_id'], unique=False)
    op.create_table('grammar_corrections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grammar_id', sa.UUID(), nullable=False),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('user_action', postgresql.ENUM('APPROVED', 'REJECTED', name='grammar_user_action'), nullable=True),
    sa.Column('user_action_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grammar_id'], ['grammar_suggestions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_corrections_grammar_id', 'grammar_corrections', ['grammar_id'], unique=False)
    op.create_index('idx_corrections_grammar_id_uuid', 'grammar_corrections', ['grammar_id'], unique=False)
    op.create_table('task_images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_image_id', 'task_images', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_image_id', table_name='task_images')
    op.drop_table('task_images')
    op.drop_index('idx_corrections_grammar_id_uuid', table_name='grammar_corrections')
    op.drop_index('idx_corrections_grammar_id', table_name='grammar_corrections')
    op.drop_table('grammar_corrections')
    op.drop_index(op.f('ix_feed_items_user_id'), table_name='feed_items')
    op.drop_table('feed_items')
    op.drop_index(op.f('ix_user_topic_preferences_user_id'), table_name='user_topic_preferences')
    op.drop_index(op.f('ix_user_topic_preferences_topic_id'), table_name='user_topic_preferences')
    op.drop_table('user_topic_preferences')
    op.drop_index(op.f('ix_user_topic_feedback_user_id'), table_name='user_topic_feedback')
    op.drop_index(op.f('ix_user_topic_feedback_topic_id'), table_name='user_topic_feedback')
    op.drop_table('user_topic_feedback')
    op.drop_table('user_topic_categories')
    op.drop_index('ix_user_preferences_user_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_table('user_learning_insights')
    op.drop_table('user_goals')
    op.drop_index('idx_translate_texts_id', table_name='translate_texts')
    op.drop_table('translate_texts')
    op.drop_index(op.f('ix_topic_refresh_jobs_topic_id'), table_name='topic_refresh_jobs')
    op.drop_table('topic_refresh_jobs')
    op.drop_table('topic_podcast_scripts')
    op.drop_index(op.f('ix_topic_articles_topic_id'), table_name='topic_articles')
    op.drop_table('topic_articles')
    op.drop_index('idx_tone_adjustments_parent_tone_id', table_name='tone_adjustments')
    op.drop_index('idx_tone_adjustments_id', table_name='tone_adjustments')
    op.drop_table('tone_adjustments')
    op.drop_index(op.f('ix_token_usage_daily_user_id'), table_name='token_usage_daily')
    op.drop_index(op.f('ix_token_usage_daily_usage_date'), table_name='token_usage_daily')
    op.drop_index(op.f('ix_token_usage_daily_source'), table_name='token_usage_daily')
    op.drop_table('token_usage_daily')
    op.drop_index('idx_tasks_user_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_password_reset_tokens_user_id_copy1', table_name='signup_tokens')
    op.drop_index('fki_signup_tokens_user_id_fkey', table_name='signup_tokens')
    op.drop_table('signup_tokens')
    op.drop_index('idx_session_tokens_user_id', table_name='session_tokens')
    op.drop_table('session_tokens')
    op.drop_index(op.f('ix_podcast_jobs_user_id'), table_name='podcast_jobs')
    op.drop_table('podcast_jobs')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_codes_user_id'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.drop_index(op.f('ix_news_items_topic_id'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('idx_suggestions_user_id', table_name='grammar_suggestions')
    op.drop_table('grammar_suggestions')
    op.drop_index(op.f('ix_admin_notes_user_id'), table_name='admin_notes')
    op.drop_index(op.f('ix_admin_notes_admin_id'), table_name='admin_notes')
    op.drop_table('admin_notes')
    op.drop_index(op.f('ix_admin_audit_logs_resource_type'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_resource_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index('users_email_unique_active', table_name='users', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('users')
    op.drop_table('topic_categories')
    op.drop_table('topic_article_refresh_jobs')
    op.drop_table('preauth_tokens')
    op.drop_table('news_topics')
    op.drop_table('learning_goals')
    op.drop_table('admin_users')
    # Enum types are created implicitly by the ENUM columns above; drop them
    # explicitly so a subsequent upgrade does not hit 'type already exists'.
    op.execute("DROP TYPE IF EXISTS feed_item_status")
    op.execute("DROP TYPE IF EXISTS grammar_user_action")
    op.execute("DROP TYPE IF EXISTS task_status")
    op.execute("DROP TYPE IF EXISTS podcast_job_status")
    op.execute("DROP TYPE IF EXISTS ai_status")
    # ### end Alembic commands ###
