// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        break;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAdtsVBQcwM1Un76E_K5ojNwiWfSSdLMlI",
      authDomain: "sbody-tracker-beba7.firebaseapp.com",
      projectId: "sbody-tracker-beba7",
      storageBucket: "sbody-tracker-beba7.firebasestorage.app",
      messagingSenderId: "1089661853542",
      appId: "1:1089661853542:web:e0441f936b20810088f2a7",
      measurementId: "G-GTDXENJKBY");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDuwL-jtVfzhPAQPnBC0ah-wQR-Sopsdw8",
    appId: "1:1089661853542:android:c57255156e2f5c6488f2a7",
    messagingSenderId: "1089661853542",
    projectId: "sbody-tracker-beba7",
    //  databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: "sbody-tracker-beba7.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDDNBrDOL8n1T7VoH9TPDtFvbyFqZfOFdg",
    appId: "1:1089661853542:ios:02effa8924696f5088f2a7",
    messagingSenderId: "1026770433644",
    projectId: "sbody-tracker-beba7",
    //databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: "sbody-tracker-beba7.firebasestorage.app",
    //androidClientId: '1:1089661853542:ios:33be6adba551df5a88f2a7',
    iosClientId:
        '1089661853542-a5hgj63tv49pft9vifntlamlgtg1pmn1.apps.googleusercontent.com',
    iosBundleId: 'com.dorna.app',
  );
}
